# Build Configuration for Travis
# https://travis-ci.org

language:
  - cpp

jdk: oraclejdk8

matrix:
  # Show final status immediately if a test fails.
  fast_finish: true
  include:
    # Android build.
    - language: android
      os: linux
      sudo: required
      dist: precise
      env: VULKAN_SAMPLES_ANDROID=ON ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    # Linux GCC debug build.
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: VULKAN_SAMPLES_BUILD_TYPE=Debug
    # Linux GCC release build.
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: VULKAN_SAMPLES_BUILD_TYPE=Release
    # Linux Clang debug build.
    - os: linux
      compiler: clang
      sudo: required
      dist: trusty
      env: VULKAN_SAMPLES_BUILD_TYPE=Debug
    # Linux Clang release build.
    - os: linux
      compiler: clang
      sudo: required
      dist: trusty
      env: VULKAN_SAMPLES_BUILD_TYPE=Release
    # Linux GCC build for code coverage.
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
      env: VULKAN_SAMPLES_CODE_COVERAGE=ON
    # Mac OS X Clang debug build.
    - os: osx
      compiler: clang
      sudo: required
      env: VULKAN_SAMPLES_BUILD_TYPE=Debug
    # Mac OS X Clang release build.
    - os: osx
      compiler: clang
      sudo: required
      env: VULKAN_SAMPLES_BUILD_TYPE=Release

cache:
  apt: true

branches:
  only:
    - master

addons:
  apt:
    packages:
      - ninja-build
      - lcov

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23

before_install:
  # Install ninja on Mac OS X.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install ninja; fi
  # Install the appropriate Linux packages.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get -y install python3 libx11-dev libxxf86vm-dev libxrandr-dev libxcb1-dev libxcb-keysyms1-dev libxcb-icccm4-dev; fi
  # Install the Android NDK.
  - if [[ "$VULKAN_SAMPLES_ANDROID" == "ON" ]]; then export ARCH=`uname -m`; fi
  - if [[ "$VULKAN_SAMPLES_ANDROID" == "ON" ]]; then wget http://dl.google.com/android/repository/android-ndk-r12b-linux-${ARCH}.zip; fi
  - if [[ "$VULKAN_SAMPLES_ANDROID" == "ON" ]]; then unzip -u -q android-ndk-r12b-linux-${ARCH}.zip; fi
  - if [[ "$VULKAN_SAMPLES_ANDROID" == "ON" ]]; then export ANDROID_NDK_HOME=`pwd`/android-ndk-r12b; fi
  - if [[ "$VULKAN_SAMPLES_ANDROID" == "ON" ]]; then export JAVA_HOME="/usr/lib/jvm/java-8-oracle"; fi

install:
  - pip install --user nose
  - pip install --user cpp-coveralls
    # Make sure we can find the above Python packages
  - export PATH=$HOME/.local/bin:$PATH

before_script:
  - git clone https://github.com/KhronosGroup/glslang.git ../glslang
  - git clone https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers.git ../Vulkan-LoaderAndValidationLayers

script:
  - echo "$TRAVIS_OS_NAME"
  - if [[ "$VULKAN_SAMPLES_ANDROID" != "ON" ]]; then mkdir build && cd build; fi
  - if [[ "$VULKAN_SAMPLES_ANDROID" != "ON" ]]; then cmake -GNinja -DCMAKE_BUILD_TYPE=${VULKAN_SAMPLES_BUILD_TYPE:-Debug} -DENABLE_CODE_COVERAGE=${VULKAN_SAMPLES_CODE_COVERAGE:-OFF} ..; fi
  - if [[ "$VULKAN_SAMPLES_ANDROID" != "ON" ]]; then ninja; fi
  - if [[ "$VULKAN_SAMPLES_ANDROID" != "ON" ]]; then ctest -j`nproc` --output-on-failure; fi
  - if [[ "$VULKAN_SAMPLES_ANDROID" == "ON" ]]; then ./build_android.sh; fi

after_success:
  # Collect coverage and push to coveralls.info.
  # Ignore third party source code and tests.
  - if [[ "$CC" == "gcc" && "$VULKAN_SAMPLES_CODE_COVERAGE" == "ON" ]]; then
      coveralls
        --root ../
        --build-root ./
        --exclude-pattern '.+/external/'
        --exclude-pattern '.+/.+_test/.cc'
        --exclude-pattern '.+/CMakeFiles/'
        --gcov /usr/bin/gcov
        --gcov-options '/--long-file-names --preserve-paths'
        --verbose;
    fi
   - if [[ "$TRAVIS_OS_NAME" == "osx" && "$VULKAN_SAMPLES_BUILD_TYPE" == "Debug" ]]; then
        export CCC_CC=clang
        export CCC_CXX=clang++
        scan-build cmake -GNinja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug ..
        scan-build ninja;
    fi

notifications:
  email:
    recipients:
      - mrelusive@oculus.com
    on_success: change
    on_failure: always
